apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-minikube
spec:
  selector:
    app: springboot-k8s-minikube
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-minikube
spec:
  selector:
    matchLabels:
      app: springboot-k8s-minikube
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-minikube
    spec:
      containers:
        - name: springboot-docker
          image: springboot-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080